name: contracts-test

on:
  pull_request:
    paths-ignore:
      - "contracts/**"
      - ".github/**"

jobs:
  build:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
