name: deploy-api
on:
  push:
    branches: [main]
    paths:
      - "cmd/api/**"
      - "api/**"
      - ".github/**"

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
      name: deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-go@v3
          with:
            go-version: '1.19'
        - uses: actions/checkout@v2
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: ./cmd/api/deploy.sh
