name: go-test

on:
  pull_request:
    paths:
      - "merkle/**"
      - "cmd/**"
      - "api/**"
      - ".github/**"

jobs:
  build:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: test
        run: go test ./...
